from typing import Protocol, runtime_checkable


@runtime_checkable
class MemoryPort(Protocol):
    def read(self) -> str: ...
    def append(self, section: str, content: str) -> None: ...
    def edit(self, section: str, new_content: str) -> None: ...
    def clear(self) -> None: ...
